// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Event struct {
	ServerID             string
	OrganizationDate     string
	DistributionDate     string
	JoinMessageID        string
	JoinMessageChannelID string
	Notes                string
	OrganizerID          string
}

type Participant struct {
	ID            string
	ServerID      string
	SecretSantaID string
	GifteeID      string
}
