// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE server_id = ?1
`

func (q *Queries) DeleteEvent(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, serverID)
	return err
}

const deleteEventParticipants = `-- name: DeleteEventParticipants :exec
DELETE FROM participants
WHERE server_id = ?1
`

func (q *Queries) DeleteEventParticipants(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteEventParticipants, serverID)
	return err
}

const getEvents = `-- name: GetEvents :many
SELECT server_id, organization_date, distribution_date, join_message_id, join_message_channel_id, notes, organizer_id
FROM events
`

func (q *Queries) GetEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ServerID,
			&i.OrganizationDate,
			&i.DistributionDate,
			&i.JoinMessageID,
			&i.JoinMessageChannelID,
			&i.Notes,
			&i.OrganizerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantsByEvent = `-- name: GetParticipantsByEvent :many
SELECT id, server_id, secret_santa_id, giftee_id
FROM participants
WHERE server_id = ?
`

func (q *Queries) GetParticipantsByEvent(ctx context.Context, serverID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, getParticipantsByEvent, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SecretSantaID,
			&i.GifteeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO events (
	server_id,
	organization_date,
	distribution_date,
	join_message_id,
	join_message_channel_id,
	notes,
	organizer_id
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
)
ON CONFLICT(server_id) DO UPDATE SET
  organization_date = EXCLUDED.organization_date,
  distribution_date = EXCLUDED.distribution_date,
  join_message_id = EXCLUDED.join_message_id,
  join_message_channel_id = EXCLUDED.join_message_channel_id,
  notes = EXCLUDED.notes,
  organizer_id = EXCLUDED.organizer_id
RETURNING server_id, organization_date, distribution_date, join_message_id, join_message_channel_id, notes, organizer_id
`

type UpsertEventParams struct {
	ServerID             string
	OrganizationDate     string
	DistributionDate     string
	JoinMessageID        string
	JoinMessageChannelID string
	Notes                string
	OrganizerID          string
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, upsertEvent,
		arg.ServerID,
		arg.OrganizationDate,
		arg.DistributionDate,
		arg.JoinMessageID,
		arg.JoinMessageChannelID,
		arg.Notes,
		arg.OrganizerID,
	)
	var i Event
	err := row.Scan(
		&i.ServerID,
		&i.OrganizationDate,
		&i.DistributionDate,
		&i.JoinMessageID,
		&i.JoinMessageChannelID,
		&i.Notes,
		&i.OrganizerID,
	)
	return i, err
}

const upsertParticipant = `-- name: UpsertParticipant :one
INSERT INTO participants (
	id,
	server_id,
	secret_santa_id,
	giftee_id
) VALUES (
    ?1, ?2, ?3, ?4
)
ON CONFLICT(id, server_id) DO UPDATE SET
	secret_santa_id = EXCLUDED.secret_santa_id,
	giftee_id = EXCLUDED.giftee_id
RETURNING id, server_id, secret_santa_id, giftee_id
`

type UpsertParticipantParams struct {
	ID            string
	ServerID      string
	SecretSantaID string
	GifteeID      string
}

func (q *Queries) UpsertParticipant(ctx context.Context, arg UpsertParticipantParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, upsertParticipant,
		arg.ID,
		arg.ServerID,
		arg.SecretSantaID,
		arg.GifteeID,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.SecretSantaID,
		&i.GifteeID,
	)
	return i, err
}
